### ISSUE TITLE
Fix the hash implementation...

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-Lavalink#68]
the hash for python objects should not be possible to collide with container types which could hold the same data....

**Comment by Jackenmen** [comment]
Hashes must fulfil 2 conditions [[1]](https://docs.python.org/3/glossary.html#term-hashable) [[2]](https://docs.python.org/3/reference/datamodel.html#object.__hash__):
1. Two objects that are equal, must have the same hash. This means that if x == y, it must follow that hash(x) == hash(y).
2. The hash of an object must not change.

Note that the opposite of 1 ("If two object are not equal, their hash should be different.") **is not** a requirement.

`__hash__` method of `Track` object does fulfil those requirements.

[1] https://docs.python.org/3/glossary.html#term-hashable
[2] [https://docs.python.org/3/reference/datamodel.html#object.\_\_hash\_\_](https://docs.python.org/3/reference/datamodel.html#object.__hash__)

**Comment by mikeshardmind** [comment]
This is a pretty low priority change, it's unlikely anyone is storing track objects side by side with other things which are also user-defined in some way, or otherwise likely to collide under normal operation. If you want to leave it closed on that basis, I see no issue with that.

With that said:

Please be careful about quoting a spec to close things. The spec, in this case, covers what is necessary for python to handle the objects, and does not always cover all the reasons why certain things are a certain way or the real-world implications.

While the inverse is not a requirement by the spec (and shouldn't be, as any large enough data representation will potentially have collisions), not making an attempt to minimize collisions can create pathological cases when storing these objects in some container types. (hashable object lookups can actually lose their constant time performance in some cases)

I'm not going to go out of my way to link a bunch of various issues people ignoring the real world around this has caused. If you decide to dive into it, there's a reason why string hashes are not deterministic across interpreter sessions and there's a reason why attrs's default __hash__ for frozen hashable objects mixes in a unique value tied to the generated class.

Because of the nature of the track objects and normal use cases of them, it's unlikely this will cause any issues, which is why when I noticed, I opened a stub issue to remind me to handle it later. I could have been more detailed when opening this issue, or just had fixed it, or updated my own issue with "here's why I'm not bothering with a code change" and closed it.

**Comment by Jackenmen** [comment]
Sorry, I could have been more specific when I closed this, I did look into *why* attrs does this (I remembered you mentioning it) and I have mentioned this stuff internally before closing. I only quoted spec here to show that it's not a requirement from standpoint of correctness but the rest of the reasons pretty much are alike with yours.
As you said already, from typical usage of Track objects inside sets/dicts I figured that it's not very likely that someone will put a tuple and Track object in same hashtable so this isn't gonna be an issue in any situation that we (Red) will use this library in.
Nonetheless, thanks for making sure that we don't close this due to some omission.
