### ISSUE TITLE
Does not work with discord.py v2.0

### ISSUE THREAD

**Issue by FightMan01** [Cog-Creators/Red-Lavalink#98]
Discord.py v2 removes the `on_socket_response` event so the library won't work. Instead we will have the `on_raw_socket_receive` event.

**Comment by Jackenmen** [comment]
Red-Lavalink will not work with d.py 2.0 until it is actually released *and* until Red *also* supports it.

I'll keep this open for now though since it does contain helpful information and we will have to work on this eventually, thanks!

**Comment by FightMan01** [comment]
Well, I thought it :D I'm working on a solution unfortunately I can't decompress the binary data. If I figure out the solution, I will open a PR.
Also this commit can be helpful: https://github.com/Rapptz/discord.py/commit/e2250d402e8ad035b2653eb411c8e744cc9eb3bf

**Comment by Jackenmen** [comment]
We'll probably switch to `VoiceProtocol` rather than use `on_raw_socket_receive`, see #97.

Sadly, `on_socket_event_type` isn't useful for our case so the `VoiceProtocol` is probably the best we'll be able to do without hurting performance by doing zlib decompression on all events. I say "sadly" because it will take some effort to migrate to that interface, but in the long run, it would be good for us to use it anyway.
